# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06175abb6f30c16d2e9fd1015944d99b999e5f9b3c161971651ef19a0f84c4cbd80bce9c6d06ed5ed00a0202fcf46fa325cfb36c096c8e1b72dd690434814064

test:
  secret_key_base: cce1394b2c8ddddb2e15fa151e0a473ccb26327f17c5fd5023dc7018a6ccfc8432f539ad7ff01e75a963254f0f1c3d8833fbcceff4294a2be82ab470372338ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
